### ISSUE TITLE
Check&CheckAll does not clear messages properly

### ISSUE THREAD

**Issue by pedjas** [jojobear99/PopTrayU#73]
When user clicks on Check or Check All, messages are not processed properly. It seems it processes only half of messages. Each time Check is run it processes half of messages, so successful runs are needed to process them all.

This also reflects to deleting messages. After user marks messages for deletion and runs Check, it does not delete all messages.

I noticed this after updated to 5.2.6

**Comment by jojobear99** [comment]
Pedjas, are you using an IMAP or POP account? I have heard other reports of this, so I will be looking into this.

**Comment by pedjas** [comment]
I have few email accounts. Some are IMAP some POP3.

I usually use CheckAll option. Today, i wanted to check if there is difference for IMAP and POP3 accounts so i Used Check on each account separately. It did not show bug this time.

I have to wait for mailbox to fill in so I can check again.

I think this may be just displaying issue. Once, after bug showed up, I decided to exit application and restart it. After reload it showed that messages were actually processed.

**Comment by BillB1** [comment]
Just wanted to say, we are very happy with PoptrayU, but this bug remains the main annoyance.  It would be great if it could be fixed :)

**Comment by pedjas** [comment]
This annoyance is still not resolved.
