### ISSUE TITLE
Display main windows via wine in Linux-Mint - Tabs are empty

### ISSUE THREAD

**Issue by nico92GitHub** [jojobear99/PopTrayU#82]
Hello! Poptray run well, but not PoptrayU (under Linux-Mint, via wine).See attached pictures. Tabs are empty.
Somebody help me?

![2016-09-23_140458](https://cloud.githubusercontent.com/assets/22394276/18785360/10c68bbe-8198-11e6-8ae6-aea5575ef3a2.png)
![2016-09-23_140557](https://cloud.githubusercontent.com/assets/22394276/18785361/10c889dc-8198-11e6-86ff-0de62d4b5c4f.png)

**Comment by Vort** [comment]
This happens because of a bug in Wine:
[WineHQ Bugzilla - Bug 7146 &ndash; Could not rotate bitmap fonts !](https://bugs.winehq.org/show_bug.cgi?id=7146)

**Comment by nico92GitHub** [comment]
Ho! Thank you for your reply. Fortunately wine exists, but it's not perfect :)
