### ISSUE TITLE
Libraries folder needs to be updated

### ISSUE THREAD

**Issue by Vort** [jojobear99/PopTrayU#83]
For example, it contains `CoolTrayIcon.zip`, which is not compatible with Delphi XE4, mentioned here:
http://poptrayu.sourceforge.net/develop/project-dependencies/

I was able to find compatible version here:
http://tib.s.songbeamer.eu/downloads/Cooltray.zip
But I am not sure if this is the same sources as used in official builds.

**Comment by jojobear99** [comment]
Wow, yeah, sorry about that. I believe that one is the same as in the official builds. I'm uploading the copy actually used for builds to the code repository just to be on the safe side for the future ;-)
