### ISSUE TITLE
Can't configure STARTTLS accounnt 

### ISSUE THREAD

**Issue by Lennyr7** [jojobear99/PopTrayU#85]
Hi,
I'm an old user of PopTray and just installed the latest version of PopTrayU v5.2.6.
I'm having a problem to configure a perfectly working POP3 email account with STARTTLS.
I use this account on my PC (Windows 7 Pro, 32 bits) with Thunderbird v52.4.0 and it works perfectly well.
Here are the parameters used by Thunderbird:

> Server type = POP
Server name = pop.bookmyname.com
Port = 110, default = 110
User name = leon.rubinstein@mobiiuz.com
Connection security = STARTTLS
Authentification method = normal password.

Here are the parameters used in PopTrayU:

> Incoming mail server = pop.bookmyname.com
Protocol = POP3
Username = leon.rubinstein@mobiiuz.com
Use SSL/TLS = ticked
Port = 110
Advanced Connection Settings:
Authentification Mode = Password
SSL / TLS Version = Auto
STARTTLS = ticked

This configuration doesn't work.
I also used all the combinations of Advanced Settings of PopTrayU (Authentification Mode & SSL / TLS Version) but always get the same error message when I use the Test Account button:

> An error occurred.
Error Type: EIdException
Socket Error. Unable to connect.Socket Error # 11001
Host not found.

Please help!
Thanks a lot in advance,
Leon
P.S. I posted this message in the SourceForge forum under the Visitor, named Lenny, along with 2 screenshots of configuration parameters for Thunderbird (working) and PopTrayU (not working)

**Comment by jojobear99** [comment]
make sure the use ssl/tls checkbox in connection settings is set. its 
possible you could get a setting mismatch importing the account if it 
imported starttls setting but not use ssl setting

if not that, is it possible you mistyped the incoming mail server address 
adding it to poptrayu? maybe retype it to double check. or if not, i would 
try unchecking starttls and see if that works better on port 995. and if 
that doesn't work, try unchecking use ssl entirely, and see if it can 
connect insecurely or not.

host not found means it couldn't connect to the server and port combination 
specified.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by Lennyr7** [comment]
Hi Jojobear99!
First, thanks so much for getting back to me so fast!
Second, it actually worked. 👏
I think it was a misspelling, even though I couldn't see any difference. I
simply copied & pasted the server name and login name from the PopTray
config.
Anyway, it all works now, including my new STARTTLS account.
So happy to be able to continue to use this GREAT utility, that PopTray is,
now with U!🏆
Thanks again,
Leon.

P.S.
1) I noticed some new fancy types of error messages with option to edit,
disable etc. for accounts. Looks great too!

2) There's a little visual issue, not really a bug:
When I try to change the order of multiple accounts tabs on the "Mail" or
on "Accounts" tab (i.e. dragging one of the account tabs to the left or to
the right and then dropping it in order to change its position), for some
reason the program jumps to the "Rules" tab. When I return to the "Mail" or
to "Accounts" tab, the change was performed correctly. But it's strange to
get the "Rules" view in this context. It works fine with PopTray v3.2

Anyway, big thanks again!🙏👌👍
