### ISSUE TITLE
jessica brown poptrayu 5.2.6 not working

### ISSUE THREAD

**Issue by sportman10** [jojobear99/PopTrayU#88]
I can not get the pop up notifier
<img width="271" alt="poptrayu puppy" src="https://user-images.githubusercontent.com/37828984/37954041-93229414-3172-11e8-8c02-a3d5acff01ad.PNG">
 to work in poptrayu 5.2.6 in a new built computer  not working can you please tell me the fix to get it to work please get back to me

**Comment by jojobear99** [comment]
duplicate issue to forum request. closing here.
