### ISSUE TITLE
Tray icon: show unread count instead of the total number of messages

### ISSUE THREAD

**Issue by ghost** [jojobear99/PopTrayU#93]
Would it please be possible to add an option to change the tray icon behaviour so that it would show the number of _unread_ messages instead of the total number of messages in the inbox?

I know I can hide the messages marked as read by checking _Hide Viewed Messages_ in _Options_ --> _Main Window_, but that is not the same (I would still like the read messages to be listed on the Mail tab).

Thanks.

nvx

**Comment by jojobear99** [comment]
Great suggestion, it really should have an option for unread vs all for message count.

**Comment by jojobear99** [comment]
Change implemented, will be in the next release
